import type { Service, Barber, Client, Appointment, DashboardStats, RevenueData, ServiceStats } from "./types"

export const services: Service[] = [
  {
    id: "1",
    name: "Corte Masculino",
    description: "Corte tradicional com máquina e tesoura",
    price: 45,
    duration: 30,
    active: true,
  },
  {
    id: "2",
    name: "Barba",
    description: "Barba feita com navalha e toalha quente",
    price: 35,
    duration: 20,
    active: true,
  },
  {
    id: "3",
    name: "Corte + Barba",
    description: "Combo completo de corte e barba",
    price: 70,
    duration: 50,
    active: true,
  },
  {
    id: "4",
    name: "Sobrancelha",
    description: "Design de sobrancelha masculina",
    price: 20,
    duration: 15,
    active: true,
  },
  {
    id: "5",
    name: "Pigmentação",
    description: "Pigmentação de barba ou cabelo",
    price: 80,
    duration: 45,
    active: true,
  },
  {
    id: "6",
    name: "Hidratação",
    description: "Tratamento capilar com hidratação profunda",
    price: 50,
    duration: 30,
    active: true,
  },
]

export const barbers: Barber[] = [
  {
    id: "1",
    name: "Carlos Silva",
    email: "carlos@barberpro.com",
    phone: "(11) 99999-0001",
    avatar: "/barber-man-professional-portrait.jpg",
    specialties: ["Corte Degradê", "Barba"],
    active: true,
  },
  {
    id: "2",
    name: "Rafael Santos",
    email: "rafael@barberpro.com",
    phone: "(11) 99999-0002",
    avatar: "/barber-professional-portrait-male.jpg",
    specialties: ["Corte Social", "Pigmentação"],
    active: true,
  },
  {
    id: "3",
    name: "Lucas Oliveira",
    email: "lucas@barberpro.com",
    phone: "(11) 99999-0003",
    avatar: "/young-barber-portrait-professional.jpg",
    specialties: ["Corte Infantil", "Design"],
    active: true,
  },
]

export const clients: Client[] = [
  {
    id: "1",
    name: "João Pedro Almeida",
    email: "joao@email.com",
    phone: "(11) 98765-0001",
    birthDate: "1990-05-15",
    notes: "Prefere corte mais curto nas laterais",
    createdAt: "2024-01-10",
    totalVisits: 12,
    totalSpent: 540,
  },
  {
    id: "2",
    name: "Marcos Vinícius",
    email: "marcos@email.com",
    phone: "(11) 98765-0002",
    birthDate: "1985-08-22",
    createdAt: "2024-02-05",
    totalVisits: 8,
    totalSpent: 360,
  },
  {
    id: "3",
    name: "André Costa",
    email: "andre@email.com",
    phone: "(11) 98765-0003",
    birthDate: "1992-11-30",
    notes: "Cliente VIP - sempre faz combo",
    createdAt: "2024-01-20",
    totalVisits: 15,
    totalSpent: 1050,
  },
  {
    id: "4",
    name: "Felipe Rodrigues",
    email: "felipe@email.com",
    phone: "(11) 98765-0004",
    createdAt: "2024-03-01",
    totalVisits: 5,
    totalSpent: 225,
  },
  {
    id: "5",
    name: "Bruno Henrique",
    email: "bruno@email.com",
    phone: "(11) 98765-0005",
    birthDate: "1988-03-12",
    createdAt: "2024-02-15",
    totalVisits: 10,
    totalSpent: 700,
  },
]

const today = new Date()
const formatDate = (date: Date) => date.toISOString().split("T")[0]

export const appointments: Appointment[] = [
  {
    id: "1",
    clientId: "1",
    clientName: "João Pedro Almeida",
    clientPhone: "(11) 98765-0001",
    barberId: "1",
    barberName: "Carlos Silva",
    serviceId: "3",
    serviceName: "Corte + Barba",
    servicePrice: 70,
    date: formatDate(today),
    time: "09:00",
    status: "confirmed",
    createdAt: formatDate(new Date(today.getTime() - 2 * 24 * 60 * 60 * 1000)),
  },
  {
    id: "2",
    clientId: "2",
    clientName: "Marcos Vinícius",
    clientPhone: "(11) 98765-0002",
    barberId: "2",
    barberName: "Rafael Santos",
    serviceId: "1",
    serviceName: "Corte Masculino",
    servicePrice: 45,
    date: formatDate(today),
    time: "10:00",
    status: "pending",
    createdAt: formatDate(new Date(today.getTime() - 1 * 24 * 60 * 60 * 1000)),
  },
  {
    id: "3",
    clientId: "3",
    clientName: "André Costa",
    clientPhone: "(11) 98765-0003",
    barberId: "1",
    barberName: "Carlos Silva",
    serviceId: "3",
    serviceName: "Corte + Barba",
    servicePrice: 70,
    date: formatDate(today),
    time: "11:00",
    status: "confirmed",
    notes: "Cliente VIP",
    createdAt: formatDate(new Date(today.getTime() - 3 * 24 * 60 * 60 * 1000)),
  },
  {
    id: "4",
    clientId: "4",
    clientName: "Felipe Rodrigues",
    clientPhone: "(11) 98765-0004",
    barberId: "3",
    barberName: "Lucas Oliveira",
    serviceId: "2",
    serviceName: "Barba",
    servicePrice: 35,
    date: formatDate(today),
    time: "14:00",
    status: "pending",
    createdAt: formatDate(today),
  },
  {
    id: "5",
    clientId: "5",
    clientName: "Bruno Henrique",
    clientPhone: "(11) 98765-0005",
    barberId: "2",
    barberName: "Rafael Santos",
    serviceId: "5",
    serviceName: "Pigmentação",
    servicePrice: 80,
    date: formatDate(new Date(today.getTime() + 1 * 24 * 60 * 60 * 1000)),
    time: "09:30",
    status: "confirmed",
    createdAt: formatDate(today),
  },
]

export const dashboardStats: DashboardStats = {
  totalRevenue: 12450,
  totalAppointments: 187,
  totalClients: 89,
  averageTicket: 66.58,
  revenueGrowth: 12.5,
  appointmentsGrowth: 8.3,
}

export const revenueData: RevenueData[] = [
  { month: "Jan", revenue: 8500, appointments: 120 },
  { month: "Fev", revenue: 9200, appointments: 135 },
  { month: "Mar", revenue: 10100, appointments: 148 },
  { month: "Abr", revenue: 9800, appointments: 142 },
  { month: "Mai", revenue: 11200, appointments: 165 },
  { month: "Jun", revenue: 12450, appointments: 187 },
]

export const serviceStats: ServiceStats[] = [
  { name: "Corte + Barba", count: 78, revenue: 5460 },
  { name: "Corte Masculino", count: 65, revenue: 2925 },
  { name: "Barba", count: 32, revenue: 1120 },
  { name: "Pigmentação", count: 15, revenue: 1200 },
  { name: "Sobrancelha", count: 22, revenue: 440 },
  { name: "Hidratação", count: 18, revenue: 900 },
]

export const availableTimeSlots = [
  "09:00",
  "09:30",
  "10:00",
  "10:30",
  "11:00",
  "11:30",
  "14:00",
  "14:30",
  "15:00",
  "15:30",
  "16:00",
  "16:30",
  "17:00",
  "17:30",
  "18:00",
  "18:30",
  "19:00",
]
